version: '3.8'

services:
  aistocktrack:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add data collection scheduler
  data-collector:
    build: .
    command: python scripts/collect_data.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - aistocktrack
    restart: "no"
    profiles:
      - collection

# Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - aistocktrack
    restart: unless-stopped
    profiles:
      - production

volumes:
  data:
  logs: